phase2/grunt-drupal-tasks

example/composer.json

Anthony Ferrara suggested https://github.com/Roave/SecurityAdvisories should be added to all application composer.json files, and it makes a lot of sense to me. This project processes a security advisory database and produces a composer.json file that specifies package conflicts with insecure packages. As a result it will break composer update and composer require operations that include the insecure packages.
This doesn't really get us much for the tools we are proposing be used, as they are unlikely to have a problematic security issue, but since we are suggesting our composer.json file be a starting place, it seems like a really good practice to recommend.

Add SecurityAdvisories check to promote best practices

---

tasks/bundler.js

Update bundler task aliases to wrap new shell target.

---

CONFIG.md
bootstrap.js

Help task requires configuration be loaded after bootstrap.js and before zzz_help.js is processed. This change allows projects to introduce custom task descriptions in Gruntfile.json so bootstrap.js picks it up.

Allow defaulting help descriptions in project Gruntconfig.json

---

CONFIG.md
tasks/quality.js

Simple override to specify that PHPCS failures should fail the build. Useful for strict projects. Waiting on Travis for actual testing.

Allow Gruntconfig to specify phpcs failures throw error.

---

tasks/package.js

This configuration will default to including all dotfiles except the .gitkeep files that are present by default in the example project.

Produce a tarball with .htaccess and other dotfiles. Fixes #113.

---

package.json

http://blog.nodejs.org/2013/02/07/peer-dependencies/
Adjusted the version to better represent this as a compatibility statement.

grunt is a peer dependency.

---

EXTEND.md

Fixing the EXTEND.md documentation for the correct file to add override JavaScript code.

Fixing file name in the EXTEND.md documentation

---

CONFIG.md

Fixes #70 
The warning reported in #70 is really just because my project Gemfile doesn't specify any JSON parsing library, and the default one is acknowledged not good. This drops the Gemfile information into the middle of the theme configuration docs as that's where it's currently most relevant.

Added documentation on Gemfile setup.

---

tasks/bundler.js

Changing bundle install default options to install gems to vendor/bundle/ and binaries to bin/.

Changing bundle install default path options

---

CONFIG.md
bootstrap.js
lib/gdt.js
lib/help.js
package.json
tasks/behat.js
tasks/bundler.js
tasks/clean.js
tasks/composer.js
tasks/drush.js
tasks/help.js
tasks/package.js
tasks/quality.js
tasks/theme.js
tasks/watch.js

Fixed #118 
This branch removes most of the code from what was tasks/zzz_help.js and instead defines a small library module that provides a means for any other code loaded by grunt to push help content into the availabletasks plugin before the task is executed.
This also demonstrates a GDT helper module loader pattern so we don't need lots of requires everywhere. I think we may be able to do something clever like attaching gdt to grunt in bootstrap, but I thought to leave that notion alone for now.
Note that this still needs a documentation update, and completely discards both the pull-based mechanism we had before, as well as the more recent Gruntconfig-based help. I think it's reasonable to put back the Gruntconfig help if we want it, but would kind of like to just drop it as this is …

Implement push instead of pull-based approach to help

---

tasks/drush.js

Updating db-url for the drush:liteinstall command to ensure the sqlite database is saved within the build directory.

Updating db-url for the drush:liteinstall

---

bootstrap.js

This snippet currently overwrites any settings specified in Gruntconfig.json. [lodash documentation](https://github.com/lodash/lodash/blob/2.4.1/doc/README.md#_assignobject-source-callback-thisarg)

Merge defaults for buildpath correctly

---

CHANGELOG.md
README.md
example/Gruntconfig.json
lib/util.js
tasks/drush.js
test/build.js
test/test_assets/Gruntconfig.json

This change switches from Gruntconfig.json-based Drush make concurrency to something dynamic. It leverages the safe concurrency algorithm from the grunt-concurrent plugin and injects that into the assembly of the make parameters.
In case someone doesn't like the default, it also allows manually specifying `--concurrency=#` in the command-line invocation to override. Along the way I went ahead and added flag documentation to the README.
**BC Break: I couldn't find a graceful way to allow the Gruntconfig to retain override capability over this parameter, but given the sensitivity of this functionality across environments it struck me as probably not as useful as having the CLI option anyway.**
Couldn't easily run the new test, so letting Travis report on it.
Fixes #103

Dynamic Concurrency [BC Break]

---

tasks/theme.js
test/test_assets/src/themes/example_theme/config.rb
test/test_assets/src/themes/example_theme/sass/ie.sass
test/test_assets/src/themes/example_theme/sass/ie.scss
test/test_assets/src/themes/example_theme/sass/print.sass
test/test_assets/src/themes/example_theme/sass/print.scss
test/test_assets/src/themes/example_theme/sass/screen.sass
test/test_assets/src/themes/example_theme/sass/screen.scss

Also, switches example_theme in test/test_assets from using sass to scss.
Resolves #109.

Support .sass files in watch:compile-theme file scanner

---

.travis.yml
bootstrap.js
package.json
tasks/help.js
tasks/notify.js
tasks/theme.js

This change adds greater complexity and reliance on the internals of the `grunt --help` system. However, that code seems pretty stable and changes are likely to be along the line of deprecating some of our changes here. I've come to the conclusion that the better experience is worth the code debt.
I copied the [output to a fancy gist](https://gist.github.com/grayside/06c412d4018da13d46af) to facilitate review.
Fixes #65

Upgrades to 'grunt help'

---

tasks/copy.js

Tells the files glob to include dot files in all directories. The tempbuild copy process did not automatically glob dotfiles included in downloaded modules when it copies to the build destination.

Allow tempbuild copy to copy dot-files.

---

CONFIG.md
tasks/quality.js

Adding Gruntconfig.json setting to override the paths included/excluded from phplint PHP code syntax validation.

Allow configuring phplint source paths

---

bootstrap.js
package.json
tasks/quality.js
tasks/watch.js

When running `grunt build` or `grunt watch` to check code quality, we are only concerned with recent changes that may require action. `grunt analyze` is available to run comprehensive checks on the codebase and generate large reports on findings.
This branch converts `grunt validate` from a standard alias to one that can take a single sub-parameter, meaning we now have `grunt validate` for the behavior we know and love and `grunt validate:newer` as a task that prefaces the validation tasks with 'newer:' so they can be run more efficiently.
This alternate syntax has been swapped into watch and default configuration.
Achieving this required fixing grunt-phpcs support for grunt-newer. We are now using a fork off the completely refactored 0.4.0 version of grunt-phpcs. There were several bugs …

Use "newer" with validate tasks in build process and watch

---

.travis.yml
CONFIG.md
tasks/make.js
tasks/serve.js
test/test.sh

This PR defines a new task: grunt serve. It's got a couple variations built-in. See change for details.
Fixes #164, #150.
@arithmetric @mikeyp

Add a grunt serve task to official support drush runserver.

---

CHANGELOG.md
CONFIG.md
tasks/copy.js
tasks/package.js

The package command has been great, but it's tied very tightly to the production of tarball archives. Those archives are great for rsync deployment use cases, but are pretty limiting for other deployment mechanisms, such as those driven by git.
This change constructs the "code export" package as a normal directory and provides some more config to determine the top-level sub-directories so it can be adapted to different PaaS systems. Now your projects have a less prescriptive foundation for how deployment can be done.
Note that this does represent a B/C break for anyone using the existing package functionality to create archives. That functionality is preserved via `grunt package:compress`. We do our best to avoid breaks like this but we are still `< 1.0`.
This change should facilitate …

Decouple package generation from archive creation.

---

tasks/serve.js

Fixing error with 'grunt serve' due to drush:serve not being defined.
See: https://gist.github.com/arithmetric/89cbe01cf6063af8e1be

Fixing error with 'grunt serve'

---

tasks/behat.js

Ensure that Behat is run with the process's environment variables in addition to ones added by the Behat task.
@peterschuelke reported an issue where Behat failed to run through Grunt Drupal Tasks with the command: `/bin/sh -c vendor/bin/behat -c ./test/behat.yml --tags ~@wip ././test/features/dashboard.feature` but could be run manually with: `vendor/bin/behat -c ./test/behat.yml --tags ~@wip ././test/features/dashboard.feature`. Another environment had an issue running Behat where it reported php not being found.
After applying this patch, Behat was able to run through Grunt Drupal Tasks using the 'sh -c' shell wrapper.

Run Behat with process env vars

---

tasks/scaffold.js
test/build.js
test/test_assets/src/libraries/example_lib/example.md
test/test_assets/src/libraries/example_lib/test.php
test/test_assets_d8/src/libraries/example_lib/example.md
test/test_assets_d8/src/libraries/example_lib/test.php

This adds symlinking of libraries in `src/libraries` as part of the default scaffold task.
You can either manually include whatever libraries your code requires, or if you're using something fancy like [Bower](http://bower.io/), just point that to the `src/libraries` directory in your `.bowerrc`.

symlink libraries as part of scaffolding

---

.travis.yml
test/test_assets_d8/src/project.make

Switch to using Travis's container-based infrastructure, and add more PHP versions to the config.

Use Travis containers and test more PHP versions

---

tasks/scaffold.js

If drush throws a fatal error during `grunt scaffold` it is currently hidden:
```
Running "scaffold" task
drush status failed with code 255
Detected Drupal 0 codebase.
Fatal error: Cannot load Drush status for built Drupal docroot.
```
with this change, the error is displayed:
```
Running "scaffold" task
drush status failed with code 255
Detected Drupal 0 codebase.
Fatal error: Cannot load Drush status for built Drupal docroot.
Error: Drush command terminated abnormally due to an unrecoverable error.                                                                                                        [error]
Error: Cannot redeclare GuzzleHttp\Psr7\str() (previously declared in /Users/jhedstrom/work/p2/drupal-ci-test/vendor/guzzlehttp/psr7/src/functions.php:17) in …
```

Display error thrown by drush.

---

.travis.yml

The PHP 5.4/ Drupal 8 build is failing over in #187 (not sure why it isn't failing without that). This excludes building Drupal 8 on the PHP 5.4 environment.

Do not test Drupal 8 on PHP 5.4

---

tasks/quality.js

This just expands the file globbing done on `phpcs` and sees if there's not 0 files before setting the config and adding it to the validate and analyze task. The diff is best [viewed with no whitespace](https://github.com/phase2/grunt-drupal-tasks/pull/192/files?w=0) as it's really just wrapping the code in `if (grunt.file.expand(phpcs).length !== 0) {}`. This should resolve #174

Prevents phpcs tasks being added if no files

---

.travis.yml
test/test.sh

Did not look into why these combinations are taking more time, but the mocha default timeout of 2 seconds is being fairly routinely reached. I have bumped the limit to 10 seconds here and observed tests passing.
@arithmetric @jhedstrom

Fix test failures on PHP 5.5+ for Drupal 8

---

tasks/quality.js

If the theme has a validate task of it's own set in the theme scripts, then let's exclude it from GDT's `grunt:validate`.

Exclude theme from validate if it supplies it's own validate

---

bootstrap.js

In working in a local mounted filesystem context the newer:drushmake task in the default build was typically failing to detect the makefiles as actionable. On investigation, this appears to be because a mounted directory to build/html is setting the timestamp for an otherwise empty directory.
grunt-newer does not have an option to override the destination path to effectively hack the timestamp for comparison, so I've instead tweaked our default task to conditionally exclude the `newer:` flag if index.php is missing.
Not only will this avoid errors for the specified mounted directory problem, it will also allow the default build process to proceed if someone manually removes build/html contents without deleting the build/html directory itself.
cc @arithmetric

Lacking an index.php, do not run drushmake with newer.

---

tasks/install.js

The new grunt install functionality had two problems.
1. The code was using a blend of `config.project.db` and `config.install.db`, which led to some mysterious hangs. I have standardized on the documented `config.project.db`.
2. `drush:updb` was not defined. I have remedied that.
With these changes, grunt install from an existing database export seems to work.
@jhedstrom

Fixing `grunt install` via dbload

---

lib/init.js
test/library.js

@arithmetric @jhedstrom 
We were clobbering the profile setting with the previous implementation. Now we can supported nested config settings in the "magic conf" loader.

Properly use and allow 'magic override' of project.db setting.

---

tasks/quality.js

If I do this:
```
yo gadget --use-master
grunt
```
I get this error:
```
Running "eslint:validate" (eslint) task
Could not find any files to validate.
Warning: Task "eslint:validate" failed. Used --force, continuing.
```
This PR doesn't let the `eslint:validate` task get added to `validate` or `analyze` unless there are files to test. It's implement the same way that I solved this problem for `phpcs` in #192

ensuring eslint only runs if there are files to test

---

lib/drupal.js
tasks/quality.js

If `Gruntconfig.json` has `eslint: false` it does not turn it off; this fixes that. The check was looking to see if it wasn't undefined; both `true` and `false` are not undefined... so this moves it to a truthy check.

Ensuring a config setting of "eslint: false" can disable it

---

tasks/copy.js
tasks/package.js

Configuring the copy tasks to preserve file mode with 'mode: true'.
By default, grunt-contrib-copy sets the mode to 0644 when it copies files. See: https://github.com/gruntjs/grunt-contrib-copy#mode

Preserve file modes on copy tasks

---

CONFIG.md
tasks/git.js

Fixes #217 , at least the functional part. Postponing addressing the nag message.

Add config option to specific command runner in git hook scripts.

---

tasks/install.js

The scope of "this" changes in the function defined in Drupal.loadDatabaseConnection(), so this.name is undefined and the pre- and post-install tasks are never added to the task list.

Store this.name in a variable

---

tasks/quality.js

The fix is to ensure that template variables are processed before the source paths are expanded.

Fixing bug that prevents phpcs and eslint from running.

---

README.md
bootstrap.js
tasks/help.js

This PR continues work from #193, but moves the branch to this repo.

adding ability to skip `grunt:validate` step to default task

---

.travis.yml

Expands the Travis test matrix to run multiple versions of Node.js/npm using nvm (in addition to multiple versions of PHP).
This includes Node.js v0.12.x, v4.2.x, and the latest version (currently v5.x) and the version of npm provided by nvm for these releases.
Thanks to @austinpray and the approach documented here: http://austinpray.com/ops/2015/09/20/change-travis-node-version.html

Expand Travis tests to run other versions of Node.js/npm

---

example/.eslintrc
tasks/quality.js

Reorganize quality.js load to configure the various tasks, but not actually identify which will run until the analyze or validate task callback is invoked by grunt. This way operations like the file check to see if eslint should run won't be operated until you run `grunt validate`, rather than running freely on such commands as `grunt help`.

Defer task identification on validate and analyze operations.

---

CONFIG.md
example/.eslintrc
tasks/quality.js

This adds a more restrictive set of default validation patterns, avoiding excessive globbing particularly in locations that might contain node_modules or similarly large directory trees. Although the existing patterns exclude these large directories from linting, patterns that match these directories (inclusive or exclusive) incur a filesystem stat which can decrease performance, especially with the recursive nature of node_modules with npm < 3. 
The summary of changes is:
1. No top-level globstar in any pattern to avoid recursing through `src/themes`, exclusive or inclusive
2. Scope php validation to the modules & profiles directories **only**.
3. Limit eslint to `themes/<theme_dir>/js` to avoid globbing through node_modules and bower_components.
4. Adjusted some defaults for common …

Scale back default validation patterns for phpcs/phplint and eslint

---

README.md
package.json

Since the role of peer dependencies is changing in npm and they interfere with new releases of Grunt (prompted by #236), let's remove the peer dependencies section of package.json.
The example package.json includes a dependency on grunt, so the need for the peer dependency in Grunt Drupal Tasks is not clear.

Removing peer dependencies

---

lib/util.js
npm-shrinkwrap.json
package.json
tasks/copy.js
tasks/make.js

Picking up from https://github.com/phase2/grunt-drupal-tasks/pull/235.
This change preserves copy:tempbuild, uses it on Windows, and on non-Windows environments switches to rsync. I thought about fancier rsync detection, but came to the conclusion I couldn't effectively test the detection mechanism itself.
As part of making this logic, I moved the configuration of drushmake build steps into the global config for our "drushmake" task. This means any use of `grunt.config.set('drushmake.options.tasks', {})` can overwrite the build process, a bit more flexible than the current requirement in bouncing around the registered drushmake task.

Faster rsync for tempbuild step in non-Windows environments.

---

tasks/install.js

Lately I've been finding that drush cannot always recognize Drupal based on the current working directory. This is local to my machine and to several other developers I've been working with. Very strange behavior, and this change does not fix it. However, I have noted that if you use the --root option you can sidestep this problem, which should at least mitigate the problem in our primary tooling while the real issue is addressed.

Use --root to set docroot path in lieu of working directory.

---

tasks/quality.js

`grunt validate:staged`, which is used by the githooks system, chokes if a theme is configured because there's nothing that can be done with `staged:themes:<name>:validate`.
This change causes tasks that are prefixed `themes:` to be pulled from the `validate:staged` handling.

Remove theme validate from validate:staged.

---

tasks/composer.js

Optimizes performance for rare dependency changes and CI that cleans the vendor directory. Note the --prefer-dist option means attempting to make more use of release tarballs, in the past this could lead to hitting Github API limits, but in the last couple weeks Github decided to remove those limits for use cases such as composer.
Fixes #253 
@jhedstrom @arithmetric

Improve performance and cacheability of composer install.

---

tasks/make.js

The existing implementation of newer does not support files that end in .make.yml, which is the current behavior by default for Gadget.

newer for make: Add support for make.yml file extension.

---

.travis.yml
tasks/copy.js
tasks/package.js
test/build.js
test/test.sh

Adds the `follow: true` option for node-glob to ensure it follows symlinks into directories for relevant copy tasks. This fixes an issue where the output of `grunt package` did not include files targeted by symlinks, like src/modules from sites/all/modules/custom.
Also adds test coverage for the build and package tasks.
Fixes #274.

Fix packaging with Grunt v1 and G-D-T v0.11

---

tasks/quality.js

This adds the additional set of best practices in the Coder module to our PHPCS processing. Since it can lead to new failures for existing projects, specifically targeting the 1.0 branch.
I have tested that this executes, and runs with both commands, but did not see any warnings from the DrupalPractice scanner to confirm it.

Add DrupalPractice standard to phpcs analysis.

---

test/test_assets_d8/composer.json

In #259 we pinned the Drush version in example/composer.json to ^8 to avoid errors in pulling from HEAD of Drush 9. Unfortunately, we previously missed the D8 variant of the composer.json used in the tests.
This [Travis Build](https://travis-ci.org/phase2/grunt-drupal-tasks/jobs/130415676) for #278 demonstrates the issue.
This change will fix test failures for both master and 1.0-pre.
Of secondary note, looks like Drush is switching to use [Robo](https://github.com/Codegyre/Robo), and Travis is running builds with XDEBUG enabled, which [significantly slows down Composer performance](https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer)

Pin D8 test assets to use Drush 8.x

---

tasks/quality.js

We are currently traversing into the site files directory for phplint. Let's stop doing that, as it can be a significant performance overhead for large sites, and in the case of one broken moment in Drupal 8 development, the basis to fail phplint validation on the codebase because a broken PHP file was dropped in the files directory.
Is there a one line way to specify "two levels deep, no more"?
@mdeltito

Do not traverse sites sub-directories on quality tasks.

---

CHANGELOG.md
docs/10_BUILD.md
docs/40_testing.md
example/Gruntconfig.json
lib/drupal.js
tasks/behat.js
tasks/quality.js
test/test_assets/Gruntconfig.json
test/test_assets_d8/Gruntconfig.json

- Exposing binary paths (phpcs, phpmd, drush, behat) as configuration options in Gruntconfig.json.
- Adding default values for Composer-installed dependencies.
Resolves #102. Also relates to #169 and #30.

Making binary paths configurable with defaults

---

tasks/package.js
test/test_assets_d8/Gruntconfig.json

Rebuild package without dev dependencies

---

bootstrap.js
tasks/composer.js

- Only run the `composer:drupal-scaffold` task if it is defined in the
`composer.json` scripts section.
This fixes an issue where D7 builds (or D8  builds without the `drupal-scaffold` script defined) would fail with:
```
[Symfony\Component\Console\Exception\CommandNotFoundException]
Command "drupal-scaffold" is not defined.
Warning: Task "composer:drupal-scaffold" failed. Use --force to continue.
Aborted due to warnings.
```

Conditionally run composer:drupal-scaffold.

---

bootstrap.js
tasks/composer.js

- Under certain conditions, the raw `composer.json` is not evaluated as
JSON, so explicitly parse the file.
- The `grunt.task.exists` command wasn't working under certain
conditions, so `grunt.config.get` is used instead.

Fixes missing composer:drupal-scaffold command.

---

example/Gruntconfig.json
tasks/package.js
test/build.js
test/test_assets_d8/Gruntconfig.json

Updates to feature/package_rewrite_composer:
- Regenerates Drupal docroot autoload.php if needed
- Allow packages.dest configuration to be optional
- Changes example and test configuration's package docroot dest to "html" so package directory should include "html" (docroot), vendor, composer.json, composer.lock
@mike-potter Please review these changes against #297.

Updates to feature/package_rewrite_composer

---

example/Gruntconfig.json
tasks/package.js
test/build.js
test/test_assets_d8/Gruntconfig.json

I implemented the approach suggested by arithmetic.  Comments welcome.

Allow changing vendor path for package output

---

tasks/quality.js

Adding check that phpcsConfig and eslintConfig are defined to prevent an error that aborts the job if these settings are not defined in Gruntconfig.json.
Currently, if phpcsConfig or eslintConfig are excluded from the Gruntconfig.json file, the validate task fails with:
```
Running "validate" task
Warning: Cannot read property 'validate' of undefined Use --force to continue.
Aborted due to warnings.
```
It should be possible to disable phpcs or eslint by setting phpcsConfig or eslintConfig to false to excluding them entirely.

Fix error when disabling eslint or phpcs

---

tasks/scaffold.js

This is a fix for https://github.com/phase2/grunt-drupal-tasks/issues/304.  In Drupal 8.2 it requires the existence of the modules, libraries, profiles folders.  If there isn't any corresponding folder in /src, these top level folders were not getting created.

Ensure profile, modules, libraries directories exist

---

test/build.js

General test failures seem to be from a hidden change in eslint rules. This should fix it.

Fix eslint error in test regex.

---

tasks/quality.js

Hey there,
This makes the PHPCS/ESLint report format overridable through the Grunt options. In our case, our CI tool uses JUnit for report parsing.
Let me know if this needs anything else. Thanks!

Expose eslint/phpcs report format config

---

tasks/serve.js

The **config** prefix of the path **serve.concurrent** used on the **serve** task is missing.
Without it, there is no way of overriding the tasks that run concurrently when serving the site with _grunt_.
This commit correct the path to **config.serve.concurrent**, so it will be able to override it.

Correct path of the config.serve.concurrent configuration

---

tasks/install.js

Only pass dbUrl to Drush if set.
