phase2/grunt-drupal-tasks

tasks/quality.js

Wrap two or more analyze tasks in a concurrent process.

---

example/Gruntconfig.json

#78: Bump drush make concurrency to 16

---

example/Gruntconfig.json
tasks/quality.js

This and #92 can be merged in any order.

Move default PHPCS standard path into code.

---

package.json
test/test.sh

Add local test-runner script, usable via 'npm test'

---

CHANGELOG.md
CONFIG.md
EXTEND.md
example/.gitignore
example/Gruntconfig.json
example/composer.json
tasks/behat.js
tasks/bundler.js
test/test_assets/Gruntconfig.json

Takes another step on https://github.com/phase2/grunt-drupal-tasks/pull/117.
I've tested it backwards and forwards a bit, so it's looking pretty good. I seem to have a problem with grunt composer in my test environment, so let's see what Travis has to say.

Consolidate bundler and composer install paths and reclaim bin/ directory

---

package.json

Adding engines and other recommended fields to package json

---

CHANGELOG.md

Still needs a date, and anything I forgot or that we added before release.

Updated CHANGELOG for v0.6.0.

---

CONFIG.md

Adding documentation on starting a project with Gadget.

Introducing Gadget

---

tasks/theme.js

#181: Fixed pluralization inconsistency in themes proxying.

---

.travis.yml
CONFIG.md
lib/drupal.js
tasks/install.js
tasks/serve.js

- Task works if no database is specified
- In manual testing, the database load only loads certain tables...

Add an install task

---

CHANGELOG.md
tasks/help.js
tasks/install.js

Release docs tweaks & loaddb suppression

---

README.md

Added version support information for node and npm

Add version support information

---

tasks/quality.js

Two new enhancements to the eslint integration from v0.9 has been uncovered for otherwise empty projects configured with a theme validate task. This results in breaking the build process when the quality.js file is loaded.
The two changes are:
* Only define the eslint task if there are files that match the configured file mask for eslint processing.
* Exempt theme JS from eslint processing by Grunt Drupal Tasks if the theme has a configured validate script in the project's Gruntconfig.json.
In a newly initialized project, there are no files to process so the eslint task is not defined. However, the theme exemption code assumes the eslint task exists.
* Retain the definition of theme-specific analyze and validate tasks where they are.
* Add a new code block as part of the eslint task …

Fix null error with eslint exclusion from theme operations

---

package.json

Related to #221 by way of updating grunt-phplint.

Package Updates

---

test/test_assets_d8/composer.json
test/test_assets_d8/src/project.make

- Pins Goutte and Symfony to the correct versions

Use a D8-specific composer.json file

---

.travis.yml
lib/drupal.js
tasks/behat.js
tasks/test.js
test/test_assets_d8/Gruntconfig.json
test/test_assets_d8/src/modules/gdt_test/gdt_test.info.yml
test/test_assets_d8/src/modules/gdt_test/tests/src/Unit/PassTest.php

This is a work in progress. See the `@todo`s for next-steps.

Run Drupal tests as part of `grunt: test`

---

.travis.yml

Let's ~~fix~~ ignore some tests!

Updating Travis config to allow failures for Node 5 env

---

lib/util.js
tasks/composer.js
tasks/make.js

As noted by @mdeltito in https://github.com/phase2/generator-gadget/pull/59

util.canRsync() is a function

---

example/composer.json

Fixes #262.
If this works, the same change should be applied to Gadget. I've aimed for a specific version of Coder because standards changes in the middle of a project seem in inappropriate.

Update to PHPCS 2 and Coder 8.2.6

---

Gruntfile.js
docs/40_operations.md
tasks/quality.js
tasks/serve.js
test/create_working_copy.sh

Removing deprecated code and documentation for v1.0 release

---

tasks/package.js
tasks/quality.js

Continuing performance issues with node_modules and bower_components, this PR adds exclusions to the phpmd command and also adds a config option to extend it.

Exclude node_modules and bower_components from phpmd

---

lib/drupal.js

Use absolute path to HTML build directory.

---

.travis.yml
example/composer.json
test/test_assets/composer.json

Add a conflict with behat 3.4+, this is a dodge to address https://github.com/Behat/Behat/issues/1085

Add conflict with behat >= v3.4
